// ==========================================================================
// This is auto-generated by gf cli tool. DO NOT EDIT THIS FILE MANUALLY.
// ==========================================================================

package internal

import (
	"github.com/gogf/gf/os/gtime"
)

// User is the golang structure for table user.
type User struct {
	Id       int64       `orm:"id,primary" json:"id"`       // 自增主键
	Name     string      `orm:"name"       json:"name"`     // 昵称
	Phone    int64       `orm:"phone"      json:"phone"`    // 手机号
	Password string      `orm:"password"   json:"password"` // 密码
	CreateAt *gtime.Time `orm:"create_at"  json:"createAt"` // 更新时间
}
